Allow role changes
nsidc/usaon-vta-survey pull request #74
Opened 2023-07-31 23:52 UTC by rmarow

2023-07-31 23:59 UTC, rmarow commented on usaon_vta_survey/routes/profile.py
need to change to user.py

2023-08-01 23:25 UTC, rmarow commented on usaon_vta_survey/templates/profile.html
@MattF-NSIDC I am having difficulty here. When I click on another users profile as admin it still shows my information at the top since I am the `current_user` that is why I added the clarification there, but I want it to somewhere show me who's profile i AM looking at since the form only includes `orcid`, `biography`, `role`, and `affiliation`

2023-08-01 23:30 UTC, MattF-NSIDC commented on usaon_vta_survey/templates/profile.html
I see, yeah. I think we need to stop using `current_user` and perhaps use the `form` object to access those values?

2023-08-01 23:35 UTC, rmarow commented on usaon_vta_survey/templates/profile.html
Yeah I am messing around with it a little more now.

2023-08-02 00:04 UTC, MattF-NSIDC commented on usaon_vta_survey/templates/profile.html
We chatted on Zoom and realized why my suggestion was bad: A form object only has select fields that we want to be editable, which doesn't include the `name` or `id` of a user (those are decided by data from Google). Instead, we needed to pass in the `user` object from the route into the template.

2023-08-02 14:53 UTC, MattF-NSIDC commented on usaon_vta_survey/forms.py
> +    role_list = QuerySelectField(query_factory=possible_roles)
Since we're not implementing the drop-down yet, I think we should remove the above function and class!

2023-08-02 14:59 UTC, MattF-NSIDC requested changes

2023-08-02 14:59 UTC, MattF-NSIDC commented on usaon_vta_survey/forms.py
> +    role_list = QuerySelectField(query_factory=possible_roles)
Since we're not implementing the drop-down yet, I think we should remove the above function and class!

2023-08-02 14:59 UTC, MattF-NSIDC commented on usaon_vta_survey/forms.py
> +        exclude_fk=False,
Let's leave a comment here that explains why we're using `exclude_fk` :)

2023-08-02 14:59 UTC, MattF-NSIDC commented on usaon_vta_survey/routes/user.py
> +            raise RuntimeError("Only admins can edit users roles.")
:pinched_fingers: 

Instead of a nested `if`, could also consider `if not X and not Y` or `if not (X or Y)`. Whatever is most readable!

2023-08-02 14:59 UTC, MattF-NSIDC commented on usaon_vta_survey/routes/users.py
I think all the changes in this file should also be reverted for now for same reasons as above :)

2023-08-02 14:59 UTC, MattF-NSIDC commented on usaon_vta_survey/templates/response/data_products.html
> +{% from 'macros/forms/macros.j2' import data_product_fields %}
```suggestion
{% from 'macros/forms/misc.j2' import data_product_fields %}
```

2023-08-02 15:25 UTC, merged